spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
  datasource:
    username: root


---

spring:
  config:
    activate.on-profile: H2
  h2.console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:${spring.application.name}
    driverClassName: org.h2.Driver

---

spring:
  config:
    activate.on-profile: mysql
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${spring.application.name}


#db:
#  host: localhost:${server.port}
#  name: csm-login
#  username: ${spring.security.user.name}
#  password: ${spring.security.user.password}
